name: Check Branch Name
on:
  create:

jobs:
  check-branch-name:
    runs-on: ubuntu-latest
    if: |
      github.event.ref_type == 'branch' && 
      !contains(['main', 'master', 'development', 'dev', 'develop'], github.ref) # ref_type check ensures the job only runs for branch creation, not tags
    steps:
      - name: Check Branch Name
        run: |
          BRANCH_NAME=${GITHUB_REF#refs/heads/}
          if [[ ! $BRANCH_NAME =~ ^(features/|fixes/|releases/) ]]; then
            echo "Invalid branch name. Must start with 'features/', 'fixes/', or 'releases/'."
            exit 1
          fi
